import { DashboardItem } from 'core-lib';
import { AudioCallState } from './app.state';

export const appList: Array<DashboardItem> = [
    {
        id: 1,
        title: 'CircleMail',
        value: 'circlemail',
        subTitle: 'CircleMail_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1220404098-612x612.jpg',
        type: 'Communication',
        description: [
            'communication-description-1',
            'communication-description-2',
            'communication-description-3',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 2,
        title: 'Bubbles',
        value: 'bubbles',
        subTitle: 'Bubbles_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-527215054-612x612.jpg',
        type: 'Communication',
        description: [
            'bubble-description-1',
            'bubble-description-2',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 3,
        title: 'Aló?',
        value: 'aló?',
        subTitle: 'Aló?_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-913843364-612x612.jpg',
        type: 'Communication',
        description: [
            'alo-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 4,
        title: 'Rooms',
        value: 'rooms',
        subTitle: 'Rooms_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1322376077-612x612.jpg',
        type: 'Communication',
        description: [
            'calls-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 5,
        title: 'Databank',
        value: 'databank',
        subTitle: 'Databank_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-486421008-612x612.jpg',
        type: 'Storage',
        description: [
            'databank-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 6,
        title: 'Photos',
        value: 'photos',
        subTitle: 'Photos_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1397150482-612x612.jpg',
        type: 'Storage',
        description: [
            'photos-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 7,
        title: 'Remember_Me',
        value: 'remember me',
        subTitle: 'Remember_Me_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1306572749-612x612.jpg',
        type: 'Storage',
        description: [
            'rememberme-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 8,
        title: 'News',
        value: 'news',
        subTitle: 'News_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1089519336-612x612.jpg',
        type: 'Genuine Information',
        description: [
            'news-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 9,
        title: 'Tasks',
        value: 'tasks',
        subTitle: 'Tasks_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1163623465-612x612.jpg',
        type: 'Productivity',
        description: [
            'tasks-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 10,
        title: 'Calendar',
        value: 'calendar',
        subTitle: 'Calendar_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1054976630-612x612.jpg',
        type: 'Productivity',
        description: [
            'calendar-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 11,
        title: 'Notes',
        value: 'notes',
        subTitle: 'Notes_SubTitle',
        imageUrl: '../../../assets/apps/blockmail.png',
        type: 'Productivity',
        description: [
            'notes-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 12,
        title: 'Reminders',
        value: 'reminders',
        subTitle: 'Reminders_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1323878785-612x612.jpg',
        type: 'Productivity',
        description: [
            'reminders-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },

    {
        id: 13,
        title: 'Words',
        value: 'words',
        subTitle: 'Text-editor',
        imageUrl: '../../../assets/apps/istockphoto-1362505810-612x612.jpg',
        type: 'Words_SubTitle',
        description: [
            'words-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 14,
        title: 'Numbers',
        value: 'numbers',
        subTitle: 'Numbers_SubTitle',
        imageUrl: '../../../assets/apps/markus-winkler-_Mpp6YZytzg-unsplash_LR.jpg',
        type: 'Productivity',
        description: [
            'numbers-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 15,
        title: 'Insta+',
        value: 'insta+',
        subTitle: 'Insta+_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1203832594-612x612.jpg',
        type: 'Social Media',
        description: [
            'insta-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 16,
        title: 'Jedibank',
        value: 'jedibank',
        subTitle: 'Jedibank_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1026540484-612x612.jpg',
        type: 'Finance',
        description: [
            'bank-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 17,
        title: 'Books',
        value: 'books',
        subTitle: 'Books_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1219941189-612x612.jpg',
        type: 'Content',
        description: [
            'books-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    }, {
        id: 18,
        title: 'Art_NFT',
        value: 'art nft',
        subTitle: 'Art_NFT_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1300341704-612x612.jpg',
        type: 'Content',
        description: [
            'oracle-description-1',
        ], updatedAt: new Date(),

        disabled: false,
    },
    {
        id: 19,
        title: 'Bazaar',
        value: 'bazaar',
        subTitle: 'Bazaar_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1294997370-612x612.jpg',
        type: 'Content',
        description: [
            'art-description-1',
        ],
        disabled: false,
        updatedAt: new Date(),
    },
    {
        id: 20,
        title: 'Signatures',
        value: 'signatures',
        subTitle: 'Signatures_SubTitle',
        imageUrl: '../../../assets/apps/istockphoto-1295781771-612x612.jpg',
        type: 'Notary Services',
        description: [ 'signatures-description-1' ],
        disabled: false,
        updatedAt: new Date(),
    },

];


export const audioCallInitialState: AudioCallState = {
    callsSummary: { received: 0, recordings: 0, missed: 0, sent: 0 },
    selectedUser: -1,
    accounts: [],
    callId: '',
    outboundWindowCall: null,
};
